language: python
cache: pip
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# Install libyaml for vcr speedup?
addons:
  apt:
    packages:
      - libyaml-dev
      - unrar
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip setuptools
  - pip install .
  - pip install -r dev-requirements.txt
  - pip install -r dev-requirements-extras.txt
# command to run tests, e.g. python setup.py test
script: py.test --cov flexget --cov-report xml -n 3
after_success:
  - python-codacy-coverage -r coverage.xml
env: VCR_RECORD_MODE=none
jobs:
  include:
    - python: "2.7" # don't want to run this for each python version so picking one
      before_install: nvm install 7
      install:
        - cd flexget/ui && npm install
      script: cd nflexget/ui && npm run lint # will run tests as well when that's ready
notifications:
  email: false
  webhooks:
    urls:
    - http://n.tkte.ch/h/343/-Sl5O1RgMVaGmIAJDbblXVIc
    - https://webhooks.gitter.im/e/45c2039915b8f75f1956
    on_success: change
    on_failure: always
    on_start: never
